console.log('Teljes név ', teljesNev());
console.log('Teljes név és kor ', nevKor());
console.log('Kor ', kor(data[0]));
console.log('Születésnapok névsorrendben ', szuletesnap());
console.log('Teljes név és születésnap ', szuletesnap());
console.log('Kor szerint növekvő sorrend ', korSzerintNovekvo());
console.log('Külföldi játékosok ', kulfoldi());
console.log('Magyar játékosok ', magyar());
console.log('Kettős állampolgárok ', kettos());
console.log('Klubok ', csapatok());
console.log('Játékosok klubonként ', jatekosokACsapatokban());
console.log('Legfiatalabb játékos ', MinimumAge());
console.log('Legértékesebb játékos ', legertekesebb());
console.log('Külföldi játékosok, akik idősebbek, mint ', kulfoldiKapusokIdosebbMint(30));
console.log('Játékosok átlagos értéke ', atlag());
console.log('Átlag feletti értékű játékosok ', atlagFelettiErtek());
console.log('Átlagérték kapusok ', atlagertekKapus());
console.log('Átlagérték középcsatárok ', atlagertekKozepcsatar());
console.log('Átlagérték hátravont csatárok ', atlagertekHCsatar());
console.log('Átlagérték bal szélsők ', atlagertekBalszelso());
console.log('Átlagérték jobb szélsők ', atlagertekJobbszelso());
console.log('Átlagérték támadó középpályások ', atlagertekTamadokpalyas());
console.log('Átlagérték belső középpályás ', atlagertekBelsokpalyas());
console.log('Átlagérték védekező középpályás ', atlagertekVedekezokpalyas());
console.log('Átlagérték jobb oldali középpályás ', atlagertekJobbOldalikpalyas());
console.log('Átlagérték bal oldali középpályás ', atlagertekBalOldalikpalyas());
console.log('Átlagérték középső védő ', atlagertekKozepsoVedo());
console.log('Átlagérték bal oldali védő ', atlagertekBalOldaliVedo());
console.log('Átlagérték jobb oldali védő ', atlagertekJobbOldaliVedo());
console.log('Átlag feletti érték kapus ', atlagFelettiErtekKapus());
console.log('Átlag feletti érték középcsatár ', atlagFelettiErtekKozepcsatar());
console.log('Átlag feletti érték hátravont csatár ', atlagFelettiErtekHcsatar());
console.log('Átlag feletti érték bal szélső ', atlagFelettiErtekBalszelso());
console.log('Átlag feletti érték jobb szélső ', atlagFelettiErtekJobbszelso());
console.log('Átlag feletti érték támadó középpályás ', atlagFelettiErtekTKpalyas());
console.log('Átlag feletti érték bal oldali középpályás ', atlagFelettiErtekBKpalyas());
console.log('Átlag feletti érték védekező középpályás ', atlagFelettiErtekVpalyas());
console.log('Átlag feletti érték jobb oldali középpályás ', atlagFelettiErtekJobbKpalyas());
console.log('Átlag feletti érték bal oldali középpályás ', atlagFelettiErtekBalKpalyas());
console.log('Átlag feletti érték középső védő ', atlagFelettiErtekKpVedo());
console.log('Átlag feletti érték bal oldali védő ', atlagFelettiErtekBVedo());
console.log('Átlag feletti érték jobb oldali védő ', atlagFelettiErtekJVedo());

console.log('Játékosok értéksorrendje', erteksorrend());
console.log('Kapus értéksorrend', erteksorrendKapus());
console.log('Középcsatár értéksorrend', erteksorrendKozepcsatar());
console.log('Hátravont csatár értéksorrend ', erteksorrendHcsatar());
console.log('Bal szélső értéksorrend ', erteksorrendBszelso());
console.log('Jobb szélső értéksorrend ', erteksorrendJszelso());
console.log('Támadó középpályás értéksorrend ', erteksorrendTKpalyas());
console.log('Belső középpályás értéksorrend ', erteksorrendbKpalyas());
console.log('Védekező középpályás értéksorrend ', erteksorrendVKpalyas());
console.log('Jobb oldali középpályás értéksorrend ', erteksorrendJKpalyas());
console.log('Bal oldali középpályás értéksorrend ', erteksorrendBKpalyas());
console.log('Középső védő értéksorrend ', erteksorrendKVedo());
console.log('Jobb oldali védő értéksorrend ', erteksorrendJVedo());
console.log('Bal oldali védő értéksorrend ', erteksorrendBVedo());

console.log('Kapusok ', kapusok());
console.log('Középcsatárok ', kpcsatar());
console.log('Hátravont csatárok ', hcsatar());
console.log('Bal szélsők ', bszelso());
console.log('Jobb szélsők ', jszelso());
console.log('Támadó középpályások ', tkppalyas());
console.log('Belső középpályások ', bpalyas());
console.log('Védekező középpályások ', vkpalyas());
console.log('Jobb oldali középpályások ', jkpalyas());
console.log('Bal oldali középpályások ', bkpalyas());
console.log('Középső védő ', kpvedo());
console.log('Jobb oldali védők ', jvedo());
console.log('Bal oldali védők ', bvedo());